### update password
POST http://localhost:2333/api/update_password
Content-Type: application/json
Authorization: tomori_token

{
  "id": 1,
  "old_password": "114514",
  "new_password": "114514",
  "env": {
    "ipv6": "test",
    "device_info": "test",
    "os": "Windows"
  }
}

### update profile
POST http://localhost:2333/api/update_profile
Content-Type: application/json
Authorization: tomori_token

{
  "id": 1,
  "new_username": "takamatsu_tomori",
  "new_email": "alphazer01214@gmail.com",
  "new_avatar": "https://cdn.discordapp.com/avatars/1/1.png",
  "new_bio": "I'm takamatsu_tomori",
  "new_phone": "114514",
  "env": {
    "ipv6": "test",
    "device_info": "test",
    "os": "Windows"
  }
}

### query one user
GET http://localhost:2333/api/user/1