server:
  host: "localhost"
  port: "2333"
  mode: "test"

postgres:
  host: "server.alphazer01214.top"
  port: "5432"
  user: "tomori"
  password: "114514"
  name: "tomori_db"

redis:
  host: "server.alphazer01214.top"
  port: "6379"
  password: ""
  timeout: 3
  pool_size: 10


jwt: 
  access_token_secret: "tomori"
  refresh_token_secret: "tomori" 
  access_token_expire_time: 114514    
  refresh_token_expire_time: 114514
  issuer: "takamatsu-tomori"
